storageClasses:
  - name: aws-efs
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    provisioner: efs.csi.aws.com
    mountOptions:
      - tls
    parameters:
      provisioningMode: efs-ap
      directoryPerms: "700"