storageClasses:
  - name: aws-efs
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    parameters:
      provisioningMode: efs-ap
      directoryPerms: "700"
      gidRangeStart: "1000"
      gidRangeEnd: "2000"
      basePath: "/"